falconArdente/diploma-team_4-koh_11-practicum-android

app/src/main/java/ru/practicum/android/diploma/root/ui/RootActivity.kt
app/src/main/res/drawable/bttm_nav_favorites_icon.xml
app/src/main/res/drawable/bttm_nav_main_icon.xml
app/src/main/res/drawable/bttm_nav_team_icon.xml
app/src/main/res/layout/activity_root.xml
app/src/main/res/menu/bottom_navigation_menu.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Добавила bottom navigation view
Реализовала его видимость в фрагментах

bottom navigation view

---

app/src/main/AndroidManifest.xml
app/src/main/java/ru/practicum/android/diploma/favorites/ui/FavoritesJobsFragment.kt
app/src/main/java/ru/practicum/android/diploma/filter/ui/FilterPlaceToWorkFragment.kt
app/src/main/java/ru/practicum/android/diploma/filter/ui/FilterRegionFragment.kt
app/src/main/java/ru/practicum/android/diploma/filter/ui/FilterSettingsFragment.kt
app/src/main/java/ru/practicum/android/diploma/team/ui/DevTeamFragment.kt
app/src/main/res/layout/activity_root.xml
app/src/main/res/navigation/navigation_graph.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/main/res/values/themes.xml

Добавил "неповоротливость" экрана
Выровнял список разработчиков в алфавитном порядке Поправил именования переходов
Убрал комментарий

14 check list bugfix small

---

app/src/main/java/ru/practicum/android/diploma/network/data/dto/linked/Area.kt
app/src/main/java/ru/practicum/android/diploma/network/data/dto/linked/Contacts.kt
app/src/main/java/ru/practicum/android/diploma/network/data/dto/linked/Employer.kt
app/src/main/java/ru/practicum/android/diploma/network/data/dto/linked/Industry.kt
app/src/main/java/ru/practicum/android/diploma/network/data/dto/linked/Locale.kt
app/src/main/java/ru/practicum/android/diploma/network/data/dto/responses/AreasResponse.kt
app/src/main/java/ru/practicum/android/diploma/network/data/dto/responses/CountriesResponse.kt
app/src/main/java/ru/practicum/android/diploma/network/data/dto/responses/DictionariesResponse.kt
app/src/main/java/ru/practicum/android/diploma/network/data/dto/responses/IndustryResponse.kt
app/src/main/java/ru/practicum/android/diploma/network/data/dto/responses/LocalesResponse.kt
app/src/main/java/ru/practicum/android/diploma/network/data/dto/responses/VacancyByIdResponse.kt
app/src/main/java/ru/practicum/android/diploma/network/data/dto/responses/VacancySuggestionsResponse.kt

Поправил адреса классов в network

---

app/src/main/java/ru/practicum/android/diploma/db/data/db/VacancyDao.kt
app/src/main/java/ru/practicum/android/diploma/db/data/db/VacancyDbConvertor.kt

Исправление неправильного сохранения вакансии

Исправление неправильного сохранения вакансии

---

app/src/main/java/ru/practicum/android/diploma/db/data/db/VacancyDbConvertor.kt
app/src/main/java/ru/practicum/android/diploma/details/domain/model/VacancyDetails.kt
app/src/main/java/ru/practicum/android/diploma/details/presentation/model/.gitkeep
app/src/main/java/ru/practicum/android/diploma/details/presentation/viewmodel/VacancyDetailsViewModel.kt
app/src/main/java/ru/practicum/android/diploma/details/ui/JobDetailsFragment.kt
app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt
app/src/main/java/ru/practicum/android/diploma/network/data/mapper/VacancyDetailsMapper.kt
app/src/main/res/values/strings.xml

Поправлены мелкие косяки с деталями вакансии, добавлена связь с интерактором Favorites

Vacancy details small fixes

---

app/src/main/java/ru/practicum/android/diploma/db/data/db/AppDatabase.kt
app/src/main/java/ru/practicum/android/diploma/db/data/db/VacancyDao.kt
app/src/main/java/ru/practicum/android/diploma/db/data/db/VacancyDbConvertor.kt
app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/AreaEntity.kt
app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/EmployerEntity.kt
app/src/main/java/ru/practicum/android/diploma/db/data/db/entity/EmployerJoins.kt

Исправлена логика работы с Area

Исправление работы базы с таблицей Area

---

app/src/main/java/ru/practicum/android/diploma/search/ui/VacancyViewHolder.kt

маленький коммит с правками отображения зарплаты в фрагменте поиска

---

app/src/main/java/ru/practicum/android/diploma/network/data/dto/linked/Area.kt
app/src/main/java/ru/practicum/android/diploma/network/data/dto/linked/VacancyAtSearch.kt
app/src/main/java/ru/practicum/android/diploma/search/data/mapper/SearchVacancyConverter.kt
app/src/main/java/ru/practicum/android/diploma/search/data/repository/SearchInteractorImpl.kt
app/src/main/java/ru/practicum/android/diploma/search/domain/model/AreaModel.kt
app/src/main/java/ru/practicum/android/diploma/search/domain/model/Vacancy.kt
app/src/main/java/ru/practicum/android/diploma/search/ui/SearchJobFragment.kt
app/src/main/java/ru/practicum/android/diploma/search/ui/VacancyViewHolder.kt
app/src/main/res/layout/fragment_search_job.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

Добавил отображение города в соответствии макету

---

app/src/main/java/ru/practicum/android/diploma/details/ui/JobDetailsFragment.kt
app/src/main/java/ru/practicum/android/diploma/favorites/ui/VacancyDetailsViewHolder.kt
app/src/main/java/ru/practicum/android/diploma/search/ui/VacancyViewHolder.kt
app/src/main/java/ru/practicum/android/diploma/utils/CurrencySymbol.kt
app/src/main/java/ru/practicum/android/diploma/utils/SalaryAmountFormat.kt

Форматирование символов валюты и суммы заработной платы вынесены в отдельные функции в Utils

Currency symbols bugfix

---

app/src/main/java/ru/practicum/android/diploma/filter/ui/FilterCountryAdapter.kt
app/src/main/java/ru/practicum/android/diploma/filter/ui/FilterCountryFragment.kt
app/src/main/java/ru/practicum/android/diploma/filter/ui/FilterRegionAdapter.kt
app/src/main/java/ru/practicum/android/diploma/filter/ui/FilterRegionFragment.kt
app/src/main/res/drawable/switch_filter.xml
app/src/main/res/layout/filter_with_recycler_item.xml
app/src/main/res/layout/fragment_filter_with_recycler.xml
app/src/main/res/navigation/navigation_graph.xml
app/src/main/res/values/strings.xml

+немного видимости в фрагментах(потом изменить по желанию)

39_адаптер и вьюхолдер для выбора страны и выбора региона

---

app/src/main/java/ru/practicum/android/diploma/network/data/HeadHunterRepository.kt
app/src/main/java/ru/practicum/android/diploma/network/data/RetrofitBasedClient.kt
app/src/main/java/ru/practicum/android/diploma/network/data/api/HeadHunterApplicationApi.kt
app/src/main/java/ru/practicum/android/diploma/network/data/dto/HeadHunterRequest.kt
app/src/main/java/ru/practicum/android/diploma/search/data/repository/SearchRepository.kt

.searchVacancy("Вакансия", areaId = null, industryId = null,currencyCode = null, salary = null, withSalaryOnly = false)
**===**
.searchVacancy("Вакансия")

42 Параметризованный поиск: Data-слой

---

app/src/main/java/ru/practicum/android/diploma/search/ui/SearchJobFragment.kt

убран баг с повторной загрузкой списка при переходе на другие фрагменты и обратно

убран баг с повторной загрузкой списка

---

app/src/main/java/ru/practicum/android/diploma/db/data/db/AppDatabase.kt
app/src/main/java/ru/practicum/android/diploma/db/data/db/VacancyDao.kt
app/src/main/java/ru/practicum/android/diploma/di/InteractorModule.kt
app/src/main/java/ru/practicum/android/diploma/di/ViewModelModule.kt
app/src/main/java/ru/practicum/android/diploma/filter/data/mapper/.gitkeep
app/src/main/java/ru/practicum/android/diploma/filter/data/repository/FilterStorageRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/filter/data/storage/SharedPrefsStorage.kt
app/src/main/java/ru/practicum/android/diploma/filter/domain/api/.gitkeep
app/src/main/java/ru/practicum/android/diploma/filter/domain/api/FilterDictionariesInteractor.kt
app/src/main/java/ru/practicum/android/diploma/filter/domain/api/FilterStorageInteractor.kt
app/src/main/java/ru/practicum/android/diploma/filter/domain/impl/FilterDictionariesInteractorImpl.kt
app/src/main/java/ru/practicum/android/diploma/filter/domain/impl/FilterStorageInteractorImpl.kt
app/src/main/java/ru/practicum/android/diploma/filter/domain/impl/FilterStorageInteratorImpl.kt
app/src/main/java/ru/practicum/android/diploma/filter/domain/impl/FilterStorageRepository.kt
app/src/main/java/ru/practicum/android/diploma/filter/presentation/model/.gitkeep
app/src/main/java/ru/practicum/android/diploma/filter/presentation/model/IndustryWithCheck.kt
app/src/main/java/ru/practicum/android/diploma/filter/presentation/state/FilterIndustryState.kt
app/src/main/java/ru/practicum/android/diploma/filter/presentation/state/FilterSettingsState.kt
app/src/main/java/ru/practicum/android/diploma/filter/presentation/viewmodel/FilterIndustryViewModel.kt
app/src/main/java/ru/practicum/android/diploma/filter/presentation/viewmodel/FilterSettingsViewModel.kt
app/src/main/java/ru/practicum/android/diploma/filter/ui/FilterIndustryAdapter.kt
app/src/main/java/ru/practicum/android/diploma/filter/ui/FilterIndustryFragment.kt
app/src/main/java/ru/practicum/android/diploma/filter/ui/FilterSettingsFragment.kt
app/src/main/java/ru/practicum/android/diploma/search/ui/SearchJobFragment.kt
app/src/main/res/values/strings.xml

Настроена работа фрагментов: FilterIndustryFragment, FilterSettingsFragment
Настроена работа viewModel: FilterIndustryViewModel, FilterSettingsViewModel
Скорректирована работа: FilterIndustryAdapter

44 Настройка работы фильтров (Отрасль, Общий фильтр)

---

app/src/main/java/ru/practicum/android/diploma/search/data/repository/SearchInteractorImpl.kt
app/src/main/java/ru/practicum/android/diploma/search/domain/api/SearchInteractor.kt
app/src/main/java/ru/practicum/android/diploma/search/presentation/viewmodel/SearchViewModel.kt
app/src/main/java/ru/practicum/android/diploma/search/ui/SearchJobFragment.kt

убран баг с дублированием айтемов в поиске

52 bag fix2

---

app/src/main/java/ru/practicum/android/diploma/details/presentation/JobDetailsFragment.kt
app/src/main/java/ru/practicum/android/diploma/details/presentation/viewmodel/VacancyDetailsViewModel.kt
app/src/main/java/ru/practicum/android/diploma/favorites/presentation/FavoritesJobsFragment.kt
app/src/main/java/ru/practicum/android/diploma/filter/presentation/FilterSettingsFragment.kt
app/src/main/java/ru/practicum/android/diploma/root/presentation/RootActivity.kt

nulls of _binding

---

app/src/main/java/ru/practicum/android/diploma/filter/data/repository/FilterDictionariesRepositoryHHNetworkClientBased.kt
app/src/main/java/ru/practicum/android/diploma/filter/domain/impl/FilterDictionariesRepository.kt
app/src/main/java/ru/practicum/android/diploma/filter/presentation/FilterCountryFragment.kt
app/src/main/java/ru/practicum/android/diploma/filter/presentation/FilterRegionFragment.kt
app/src/main/java/ru/practicum/android/diploma/filter/presentation/mapper/.gitkeep
app/src/main/java/ru/practicum/android/diploma/filter/presentation/state/AreaFilterState.kt
app/src/main/java/ru/practicum/android/diploma/filter/presentation/viewmodel/CountryFilterViewModel.kt
app/src/main/java/ru/practicum/android/diploma/filter/presentation/viewmodel/RegionFilterViewModel.kt

…ны. Поправлена логика ввода по тексту в регионах (число символов должно быть больше 2)

67 добавлена обработка различных ошибок на экранах фильтра стран и регионов

---

app/src/main/java/ru/practicum/android/diploma/filter/presentation/FilterIndustryFragment.kt
app/src/main/java/ru/practicum/android/diploma/filter/presentation/FilterSettingsFragment.kt
app/src/main/java/ru/practicum/android/diploma/filter/presentation/state/FilterIndustryState.kt
app/src/main/java/ru/practicum/android/diploma/filter/presentation/viewmodel/FilterIndustryViewModel.kt
app/src/main/res/layout/fragment_filter_with_recycler.xml
app/src/main/res/values/strings.xml

Добавлены состояния для ошибок и пустого списка, а так же их обработка

Скорректирована работа экрана фильтра по отраслям

---

app/src/main/java/ru/practicum/android/diploma/search/presentation/SearchJobFragment.kt
app/src/main/java/ru/practicum/android/diploma/search/presentation/state/SearchFragmentState.kt
app/src/main/java/ru/practicum/android/diploma/search/presentation/viewmodel/SearchViewModel.kt

1. Убрана LiveData на progress bar в SearchViewModel
2. Пофикшен баг, когда при стирании всей строки запускался поиск последней буквы текста, введенного до этого в поиске
3. Убран баг, когда при нажатии на синюю кнопку OK на клавиатуре (при уже полученном результате поиска и смене, например, региона) новый результат поиска прикреплялся к в низ к уже существующему списку
4. Убраны лишние подписки на LiveData
5. Убран дублирующий код

68 Убрана LiveData на progress bar и исправлены другие баги

---

app/src/main/java/ru/practicum/android/diploma/filter/presentation/FilterSettingsFragment.kt
app/src/main/java/ru/practicum/android/diploma/root/presentation/RootActivity.kt
app/src/main/java/ru/practicum/android/diploma/search/presentation/SearchJobFragment.kt
app/src/main/java/ru/practicum/android/diploma/search/presentation/viewmodel/SearchViewModel.kt
app/src/main/java/ru/practicum/android/diploma/search/ui/SearchRepeatHandler.kt

Функция повторного поиска:
Маркер в root
Контракт: SearchRepeatHandler.kt
Берёт, исполняет и чистит: поисковый фрагмент.
Выставляет фильтростроительный

75. Поисковый запрос и "Применить"

---

app/src/main/java/ru/practicum/android/diploma/network/data/repository/HeadHunterRepository.kt
app/src/main/java/ru/practicum/android/diploma/network/data/repository/RetrofitBasedClient.kt
app/src/main/res/values/strings.xml

Добаил возможность реакции на таймаут по цепочке ответа после поискового респозитория, сейчас обрабатывается как иная ошибка.

Bug fix timeout response

---

app/src/main/java/ru/practicum/android/diploma/filter/data/repository/FilterStorageRepositoryImpl.kt
app/src/main/java/ru/practicum/android/diploma/filter/domain/model/FilterGeneral.kt
app/src/main/java/ru/practicum/android/diploma/filter/presentation/FilterSettingsFragment.kt
app/src/main/java/ru/practicum/android/diploma/filter/presentation/viewmodel/FilterSettingsViewModel.kt
app/src/main/java/ru/practicum/android/diploma/search/data/mapper/SearchVacancyConverter.kt

Фильтр hideNoSalaryItems теперь может быть пустым
Добавлены проверки на null

Исправлены баги с фильтром (чекбокс)

---

app/src/main/java/ru/practicum/android/diploma/search/presentation/SearchJobFragment.kt

Исправлено определение последнего элемента в recyclerView

Исправлено определение последнего элемента в recyclerView

---

app/src/main/java/ru/practicum/android/diploma/details/presentation/viewmodel/VacancyDetailsViewModel.kt
app/src/main/java/ru/practicum/android/diploma/search/presentation/SearchJobFragment.kt

Исправление избранного

---

app/src/main/java/ru/practicum/android/diploma/details/presentation/viewmodel/VacancyDetailsViewModel.kt
app/src/main/java/ru/practicum/android/diploma/search/presentation/SearchJobFragment.kt

Favorite fix
